# Generated by Django 3.2.20 on 2023-08-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gini',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_quarter', models.CharField(max_length=10)),
                ('gini_coefficient', models.FloatField()),
                ('disposable_income_growth', models.FloatField()),
                ('median_disposable_income_growth', models.FloatField()),
                ('wage_income_growth', models.FloatField()),
                ('business_income_growth', models.FloatField()),
                ('property_income_growth', models.FloatField()),
                ('transfer_income_growth', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Gini Data',
            },
        ),
    ]
