# Generated by Django 3.2.20 on 2023-08-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0002_gini'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_quarter', models.CharField(max_length=10)),
                ('total_income', models.IntegerField()),
                ('wage_income', models.IntegerField()),
                ('business_income', models.IntegerField()),
                ('property_income', models.IntegerField()),
                ('transfer_income', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Income Data',
            },
        ),
    ]
